### ISSUE TITLE
Frame GUI for Android

### ISSUE THREAD

**Issue by a-s1299** [CS3398-betazoids-alphamales/CS3398-betazoids-S2020#11]
This will prepare the Android application for "plug-and-play" of our search algorithm and then be ready for instantiation.

**Comment by evanfestrada** [comment]
I think, for now, we can base this off our current website at a mobile device size. As we make more progress and get the it more refined, we can do redesign of a potential mobile version based off of the web version.

<img width="502" alt="Screen Shot 2020-02-24 at 3 22 26 PM" src="https://user-images.githubusercontent.com/26262596/75192282-8bd4cf00-5719-11ea-89f8-adfff7f9dd2c.png">
