### ISSUE TITLE
Frame WebApp GUI

### ISSUE THREAD

**Issue by a-s1299** [CS3398-betazoids-alphamales/CS3398-betazoids-S2020#13]
Since our product will be first implemented for a web application we would need to have this ready for connection to our database. Design and layout can be created simultaneously.

**Comment by evanfestrada** [comment]
I wouldn't mind helping with this as well. I think using Bootstrap would be a good idea, even a Bootstrap template or theme to make things go quicker. 

https://startbootstrap.com/themes/

**Comment by evanfestrada** [comment]
https://docs.google.com/presentation/d/1H3nJWtqTiYMdaJfWLd7iGyKQ_eKWjSnrIqtsADG_00g/edit?usp=sharing
