### ISSUE TITLE
Successfully connect WebApp to database

### ISSUE THREAD

**Issue by a-s1299** [CS3398-betazoids-alphamales/CS3398-betazoids-S2020#23]
This will entail making https requests, and successfully retrieving the response json file.

**Comment by evanfestrada** [comment]
fulladress....?findThis=value

**Comment by a-s1299** [comment]
Check documentation if something goes wrong. Ben and I will be making edits, and we will try to update you guys. But we should always document our functions here:
https://firebasestorage.googleapis.com/v0/b/rvrslkupdb.appspot.com/o/index.js?alt=media&token=6f7eaee2-6bab-474e-b507-38008b07e533
