### ISSUE TITLE
Set Up Database prototype functions

### ISSUE THREAD

**Issue by evanfestrada** [CS3398-betazoids-alphamales/CS3398-betazoids-S2020#7]
We need to set up our database of recipes. 

One option: https://www.thecocktaildb.com/

The other database option was a pre-built database of 1000 recipes found by Ben.

**Comment by BenjaminWalkerBond** [comment]
http://www.databasepool.com/index.php?l=product_detail&p=309

**Comment by a-s1299** [comment]
updated goals for task to fit current needs. with task we will create all necessary functions for giving the webapp functionality.  function will be intended for development, and not final release.
